server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        registration:
          sandwich-admin-client:
            provider: sandwichcloud
            client-id: sandwich-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          sandwichcloud:
            issuer-uri: http://authserver:9000
