spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

  h2:
    console:
      enabled: true

  security:
    user:
      name: test
      password: test
      roles: ROLE_ADMIN
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: sandwichcloud


sandwich:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost/sandwichcloud
    username: sandwichuser
    password: sandwichpassword

logging:
  level:
    sandwiches: WARN