spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  security:
    user:
      name: buzz
      password: infinity

  datasource:
    generate-unique-name: false
    name: sandwichcloud

sandwich:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost/sandwichcloud
    username: sandwichuser
    password: sandwichpassword

logging:
  level:
    sandwiches: WARN

sandwich:
  orders:
    pageSize: 10